export enum NOTIFICATION_TYPE {
  SUPER_ADMIN = "SUPER_ADMIN",
  ADMIN = "ADMIN",
  USER = "USER",
  MESSAGE_NEW = "MESSAGE_NEW",
}

export enum NOTIFICATION_REFERENCE_MODEL {
  USER = "User",
  NUDGE = "Nudge",
  MODE = "Mode",
}
